apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../crds
  # Namespace "icegate" is created by the IceGate Helm chart (namespace.create: true
  # in values-icegate.yaml). This secret depends on that chart being rendered in
  # the same kustomize build.
  - secret-aws.yaml
  - job-rustfs-init.yaml

helmGlobals:
  chartHome: ../../../helm

helmCharts:
  - name: rustfs
    repo: https://charts.rustfs.com/
    version: 0.8.0
    releaseName: rustfs
    namespace: infra
    valuesFile: values-rustfs.yaml

  - name: icegate
    releaseName: icegate
    namespace: icegate
    valuesFile: values-icegate.yaml
