{{- if and .Values.query.enabled .Values.query.cache.enabled .Values.query.cache.persistence.enabled (not .Values.query.cache.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icegate.cachePvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "icegate.componentLabels" (dict "context" . "component" "query") | nindent 4 }}
  {{- with .Values.query.cache.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.query.cache.persistence.accessModes | nindent 4 }}
  storageClassName: {{ include "icegate.cacheStorageClassName" . }}
  resources:
    requests:
      storage: {{ .Values.query.cache.volumeSizeLimit }}
{{- end }}
