{{- if and .Values.compact.enabled .Values.compact.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "icegate.componentName" (dict "context" . "component" "compact") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "icegate.componentLabels" (dict "context" . "component" "compact") | nindent 4 }}
  {{- with .Values.compact.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.compact.service.type }}
  selector:
    {{- include "icegate.selectorLabels" (dict "context" . "component" "compact") | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.compact.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
