apiVersion: 1

datasources:
  - name: IceGate Logs
    type: loki
    access: proxy
    url: http://query:3100
    isDefault: true
    editable: false
  - name: IceGate Metrics
    type: prometheus
    access: proxy
    url: http://query:9090
    isDefault: false
    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: false
