apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: observability
  labels:
    app.kubernetes.io/name: cadvisor
    app.kubernetes.io/component: container-metrics
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: cadvisor
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
