apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboards-icegate
    namespace: observability
    files:
      - dashboards/Icegate-Ingest-1769530183590.json
      - dashboards/Icegate-Query-1773746395045923.json
      - dashboards/Nodes-1769530183590.json

resources:
  - namespace-infra.yaml
  - namespace-observability.yaml
  - otel-collector
  - cadvisor

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 72.6.2
    releaseName: prometheus
    includeCRDs: false
    namespace: observability
    valuesFile: values-prometheus.yaml

  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.8.2
    releaseName: grafana
    namespace: observability
    valuesFile: values-grafana.yaml
